name: Start

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@master
        with:
          workflow: Mirror

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
